sudo: true
language: node_js
node_js:
  - "14"
# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
    - $TRAVIS_BUILD_DIR/.stack-work
    - $HOME/docker-cache

services:
  - docker

before_install:
  # MongoDB for test purposes
  - |
    filename=$HOME/docker-cache/saved_images.tar
    if [[ -f "$filename" ]]; then docker load < "$filename"; fi
    mkdir -p docker-cache
    docker pull mongo:4.0.4
  - docker run -d -p 27017-27019:27017-27019 mongo:4.0.4
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod +x .travis/genDoc.sh
  - chmod +x .tenv

jobs:
  include:
    - stage: "Build & Test" 
      name: "Build & Test"
      script: |
        stack build 
        stack test
      env: # setup envs for connecting to local test db
        - DB_ADDR="127.0.0.1"
        - DB_NAME="test"
        - DB_PW=""
        - DB_USER=""
        - DB_USE_REPLICA="false"
        - PORT="8080"
    - stage: "Deploy"
      script: |
        stack build
        sh .travis/genDoc.sh
      before_deploy: .travis/updateGit.sh
      deploy:
        provider: heroku
        strategy: git
