sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - docker-cache
  - $TRAVIS_BUILD_DIR/Hanabi-Backend.cabal
  - $TRAVIS_BUILD_DIR/stack.yaml.lock

services:
  - docker

before_install:
  # MongoDB for test purposes
  - |
    filename=docker-cache/saved_images.tar
    if [[ -f "$filename" ]]; then docker load < "$filename"; fi
    mkdir -p docker-cache
    docker pull mongo:4.0.4
  - docker run -d -p 27017-27019:27017-27019 mongo:4.0.4
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

jobs:
  include:
    - stage: build
      rvm: "1.0"
      name: "Build"
      script: stack build 
    - stage: test
    rvm: "1.0"
      script: stack test 
      env: # setup envs for connecting to local test db
        - TEST="test"
        - DB_ADDR="127.0.0.1"
        - DB_NAME="test"
        - DB_PW=""
        - DB_UNAME=""

        